### ISSUE TITLE
Custom es6 Module Loader

### ISSUE THREAD

**Issue by Alphapage** [joeldenning/kremling#6]
Hello,

Did you try to implement kremling in a custom module loader https://github.com/ModuleLoader/es6-module-loader/blob/master/docs/loader-extensions.md ?

And is it possible to do for kremling ?

Thanks in advance for your answers.

**Comment by internettrans** [comment]
I haven't tried to use it as a custom module loader, although to do so I think all you'd have to do is `System.translate = function (load) { return kremling.compile(load.source); }`. This assumes that `System.register` is available on the global, which is something that is not provided by es6-module-loader, but only by SystemJS. I have a really incomplete implementation of the `System.register` function here in kremling in the tests, but I wouldn't recommend using that one.

If you try it out, let me know how it goes. Kremling is still very much experimental, so no guarantees on it working properly yet.
